### ISSUE TITLE
emit properties of geofeature

### ISSUE THREAD

**Issue by beckerIGG** [pouchdb/geopouch#12]
Hi,

thx at first for fixing the temp issue. it works now perfectly. However, the spatial function just provides the id and the geometry of the objects within the specified boundingbox. Do you see a chance that the function also provides the properties of a geoobject? currently i get back the id's and afterwards i request the db again to fetch the properties of the features. Or am i doing things wrong?
Thx for any answer in advance

**Comment by calvinmetcalf** [comment]
pass include_docs: true to the query as an option
