### ISSUE TITLE
Add radius search

### ISSUE THREAD

**Issue by mfilotto** [pouchdb/geopouch#13]
Hi,
would be nice to have a radius search.

**Comment by calvinmetcalf** [comment]
internally we only use bounding boxes so we wouldn't be able to do do
anything more efficient then you would be able to by filtering out the
corners.

**Comment by mfilotto** [comment]
Thanks for your answer.
I close the issue as in memory filtering is a good solution for me

**Comment by hmendes00** [comment]
Hi @mfilotto, I know the topic is old, but do you still have the code with the solution for that? I'm new on pouchdb, so I have no idea how to proceed with that. Thank you.
