### ISSUE TITLE
work with v2 of pouchdb

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/geopouch#4]

**Comment by superlou** [comment]
Is this the PouchDB server version or the PouchDB version?  I think the client-side version is up to 5.1.

**Comment by calvinmetcalf** [comment]
this related to updating it to work with persistent indexes in pouchdb library 2.0, honestly don't know if it still works with 5.1 but I don't think any of the breaking changes apply.

**Comment by superlou** [comment]
The test suite shows all passing for both PouchDB 3.6.0 and 5.1.0.

**Comment by calvinmetcalf** [comment]
that should be expected as that aspect of pouch hasn't changed and this
issue was only left open by accident sorry about that

**Comment by superlou** [comment]
No problem, was just doing a double-check for sanity.  Thanks for the plugin!
